USE [master]
GO

/****** Object:  Database [gymDatabase]    Script Date: 16-May-23 3:46:52 PM ******/
CREATE DATABASE [gymDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gymDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\gymDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gymDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\gymDatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gymDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [gymDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [gymDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [gymDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [gymDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [gymDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [gymDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [gymDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [gymDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [gymDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [gymDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [gymDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [gymDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [gymDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [gymDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [gymDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [gymDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [gymDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [gymDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [gymDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [gymDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [gymDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [gymDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [gymDatabase] SET RECOVERY FULL 
GO

ALTER DATABASE [gymDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [gymDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [gymDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [gymDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [gymDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [gymDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [gymDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [gymDatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [gymDatabase] SET  READ_WRITE 
GO

